url: https://122e4e-mapbox.global.ssl.fastly.net
api: https://122e4e-mapbox.global.ssl.fastly.net/core
tileApi: https://api-maps-staging.tilestream.net
permalink: /:categories/:title/
baseurl: /mapping
title: Mapping with OpenStreetMap
markdown: kramdown
kramdown:
  input: GFM
exclude:
- package.json
- node_modules
- README.MD
- CONTRIBUTING.md
- test

languages:
  en: English # abbreviation: Name of native language
  es: Español
  jp: 日本語
  uk: Українська

defaults:
- scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"
# DEFAULT ENGLISH
- scope:
    path: ""
    type: "pages"
  values:
    lang: "en"
- scope:
    path: ""
    type: "posts"
  values:
    lang: "en"
# SPANISH
- scope:
    path: "es"
    type: "pages"
  values:
    lang: "es"
- scope:
    path: "es"
    type: "posts"
  values:
    lang: "es"
# JAPANESE
- scope:
    path: "jp"
    type: "pages"
  values:
    lang: "jp"
- scope:
    path: "jp"
    type: "posts"
  values:
    lang: "jp"
# UKRAINIAN
- scope:
    path: "uk"
    type: "pages"
  values:
    lang: "uk"
- scope:
    path: "uk"
    type: "posts"
  values:
    lang: "uk"
